# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  push:
    branches:
      - docker

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: singh12345akshay/devops1
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


# name: Build and push docker image

# on:
#   push:
#     branches:
#       - docker

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
    
#     - uses: actions/checkout@v3
#       name: Check out code

#     - uses: mr-smithers-excellent/docker-build-push@v6
#       name: Build & push Docker image
#       with:
#         image: image
#         tags:  latest
#         registry: singh12345akshay/devops1
#         dockerfile: Dockerfile
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v2

    #   - name: executing remote ssh commands using password
    #     uses: docker/build-push-action@v5.0.0
    #     with:
    #       # host: ${{ secrets.EC2_HOST }}
    #       docker_username: ${{ secrets.DOCKER_USERNAME }}
    #       docker_password: ${{ secrets.DOCKER_PASSWORD }}
    #       # port: ${{ secrets.PORT }}
    #       script: |
    #         docker build -t devopsimage .
    #         docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
    #         # sudo yum install git
    #         # ls  /home/ec2-user/
    #         # sudo yum update
    #         # sudo yum install git -y
    #         # sudo yum install -y nodejs
    #         # git clone https://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@github.com/singh12345akshay/devops.git
    #         # cd /home/ec2-user/devops  



