name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            # sudo yum install git
            ls  /home/ec2-user/
            sudo yum update
            sudo yum install git -y
            sudo yum install -y nodejs
            git clone https://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@github.com/singh12345akshay/Chatbot.git
            cd /home/ec2-user/Chatbot  
            # nvm use 18
            npm i
            npm run build
            nohup npm start &
              
